### ISSUE TITLE
테스트코드 동기요청,비동기요청 커버 및 Rewrite

### ISSUE THREAD

**Issue by SaidBySolo** [SaidBySolo/neispy#17]
Test code sync request added and rewrite required

**Comment by kijk2869** [comment]
동기에서 `asyncio.run`으로 비동기 함수를 실행할 수 있지만, Python 3.7+에서 동작합니다.

**Comment by kijk2869** [comment]
`loop.run_until_complete`가 차선책이 될 수 있지만, 전자를 추천하고 싶습니다.
