### ISSUE TITLE
급식정보에서 MMEAL_SC_CODE관련

### ISSUE THREAD

**Issue by GamJaChips** [SaidBySolo/neispy#21]
급식정보에서 MMEAL_SC_CODE와 관련없이 아침, 점심, 저녁이 모두 있는 학교를 검색할 때 아침값만 나옴

**Comment by SaidBySolo** [comment]
무슨학교인지 알수있을까요?

**Comment by SaidBySolo** [comment]
해당 이슈의 수정사항이 2.0.4버전부터 적용됩니다.
