### ISSUE TITLE
AttributeError: module 'neispy' has no attribute 'AsyncClient'

### ISSUE THREAD

**Issue by GamJaChips** [SaidBySolo/neispy#46]
AttributeError: module 'neispy' has no attribute 'AsyncClient' 라는 오류가 뜨는데 확인부탁드려요!

**Comment by SaidBySolo** [comment]
https://github.com/SaidBySolo/neispy#%EC%82%AC%EC%9A%A9-%EC%98%88%EC%8B%9C%EB%B9%84%EB%8F%99%EA%B8%B0

사용예시 참고해주세요
