### ISSUE TITLE
사용법 페이지의 이미지가 안보입니다.

### ISSUE THREAD

**Issue by jjh4450** [SaidBySolo/neispy#47]
https://www.koreaminecraft.net/dev_lecture/1790805
이곳 이미지가 보이지 않습니다
![image](https://user-images.githubusercontent.com/55692226/112776058-962e6e80-9079-11eb-973c-be6a2f46efd7.png)

그냥 제 컴퓨터 문제일까요?

**Comment by SaidBySolo** [comment]
해당 사이트 관리자분께 문의해놓았습니다.

다만 해당 라이브러리 자체와 무관 하기때문에 invaild처리하겠습니다.

**Comment by SaidBySolo** [comment]
사이트 쪽 문제네요. 해결할 수 없었습니다 ㅠㅠ

추후에 다시 작성하겠습니다!
