### ISSUE TITLE
학교 등등의 클래스 구현

### ISSUE THREAD

**Issue by star0202** [SaidBySolo/neispy#60]
[제 개인 포크](https://github.com/star0202/neispy)에서 작업중인 바와 같이, 원래는 schoolInfo가 `Any`를 리턴해 직접 원하는 값을 입력해야 했지만, schoolInfo가 list[School]을 리턴하고, mealServiceDietInfo가 학교 코드 대신 School을 매개변수로 받고 list[Meal]을 리턴하는 방식은 구현하시지 않은 이유가 있나요?

**Comment by SaidBySolo** [comment]
말씀주신 부분을 두 부분으로 나누어서 말씀드리겠습니다.

> [제 개인 포크](https://github.com/star0202/neispy)에서 작업중인 바와 같이, 원래는 schoolInfo가 Any를 리턴해 직접 원하는 값을 입력해야 했지만, schoolInfo가 list[School]을 리턴하고

open neis api에서 명세서를 보시면 아시겠지만 구조가 정형화 되어있지도 않고, 엄청나게 많은 인자들이 있습니다.

응답값을 래핑 할려고 시도를 할려고 했는데 도중 몇몇 문제가 생각났습니다.

* 다음과 같은 부분의 반환값을 TypedDict로 변경해야 함
https://github.com/SaidBySolo/neispy/blob/a93c94f0a61235709a7c09124770a6828236ca47/neispy/http.py#L139-L140
* 과연 속성을 안전하게 참조 할수있을까?
* 저렇게 많은 인자를 래핑하면 이점이 있을까?
  * 왜냐하면 기능을 만들때 참조하는 인자는 몇몇개밖에 없는데 저걸 전부 래핑해봤자 쓸모가 있을까?

결국 그래서 생각난것이 ``SimpleNamespace`` 객체로 래핑하는것 이였습니다.

만약 래핑을 한다면 여러 엣지 케이스를 위한 테스트 코드도 다시 작성해야 하며, 브레이킹 체인지가 될것같습니다.

> mealServiceDietInfo가 학교 코드 대신 School을 매개변수로 받고 list[Meal]을 리턴하는 방식은 구현하시지 않은 이유가 있나요?

매개변수로 객체를 받지않는 이유를 유연함과 open neis api의 형식을 존중하기 위해서입니다.

**Comment by star0202** [comment]
넴 감사합니다
